import XCTest
@testable import EVE

final class GatewayTrustEvaluatorTests: XCTestCase {
    /// The real EVE root CA is deliberately never committed to this
    /// repository (EVE/Resources/EVERootCA-README.md) — it's per-deployment
    /// and generated by eve-os. So in this test target the resource is
    /// always absent, and init must fail loudly rather than silently
    /// degrade to unpinned trust.
    func testInitThrowsWhenRootCertificateIsNotBundled() {
        XCTAssertThrowsError(try GatewayTrustEvaluator()) { error in
            XCTAssertEqual(error as? GatewayTrustEvaluator.TrustError, .rootCertificateNotBundled)
        }
    }

    func testInitThrowsForAnExplicitlyMissingResourceName() {
        XCTAssertThrowsError(
            try GatewayTrustEvaluator(resourceName: "DoesNotExist", resourceExtension: "cer")
        )
    }
}
